version:
  name: velociraptor
  version: 0.73.4
  commit: c5a3d32
  build_time: "2025-02-25T12:05:37Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/13520723553
  compiler: go1.23.6
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://10.221.1.131:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQajBGWSu5E8CYJOu1WYqaHTANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjUwMzE1MTg1NzMyWhcNMzUw
    MzEzMTg1NzMyWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCw98yRFucL4JFHsNRwfJIdW4M1QG860nVb
    CjyNDRonHn5xc7WVu8ZofXo8QO1cVhvqcSY6jWQqQ1iIT1N2K+AHpamQ2oz/gOfT
    SE4kEeTuiCdDwrzAENewAkkMr3K3bhDUbo5/6PI6sieQPj+n/hhIRzHi1mG0KbwI
    Q0r0eGSVCPHrYlAGJAQrcXZmkWTnHdOTc7SS2pkmqPZh8M2X24V9GMOIukcoCPAj
    KDbMYNricjUqQNKnoVQHHBOHl/RmjFhc794usWjogu9LyPPrp0GfkpIoejVl0/NB
    6BXkU/rFBNpsr89YYSMqQdsdvxmDdQndB9ByYDi0q8S7Pq1vGPfRAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSjmBP1rDCedXwzp4Hk2WpwcTbM
    9jAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEARaS+b8VcgQ/ENIskh/VtS9IogPlcGiFKGjezAzv1CPbQ
    jYaqWfdbMFIi/gEgxpqVtl0EtGP+VVRHlnwfu3nPbfkMMgNowH+UsNuMxQreB1yY
    VjV9xcUhL62gpcX3ovARksWW9TtU1DPBJ34FQoD7assusSkLbHJluEgvadletwpF
    sHjR92pjnps60c2FSl4k+PRXWWtCEMI50L5TI/8DVWQbtEPgLigilmiQHsHjZTEe
    b9Y/6+RqyZS8Ex+8ZWYUL7Ly5MvHVwG7/QE+k4mwp0G5koRcfWmYYXhL5hpKhmih
    UKPxm9ghv1wfcVzt/LyZIdoq/+jd9FoMsdw34LOdVw==
    -----END CERTIFICATE-----
  nonce: RvCbbeVjPSQ=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.73.4
    commit: c5a3d32
    build_time: "2025-02-25T12:05:37Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/13520723553
    compiler: go1.23.6
    system: linux
    architecture: amd64
  server_version:
    version: 0.73.4
    commit: c5a3d32
    build_time: "2025-02-25T12:05:37Z"
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
